@startuml
'https://plantuml.com/sequence-diagram


class Almoaditas{
-nombremascota:String
-nombreduenio:String
-edad: int
-especie:String
-razondevisita:String
-estadoanimal:String

+Almoaditas(nombremascota:String,nombreduenio:String,edad: int
especie:String,razondevisita:String,estadoanimal:String)
+getnombremascota():String
+getnombreduenio():String
+getint():int
+getespecie():String
+getrazondevisita():String
+getestadoanimal():String
+setestadoanimal():void

}


@enduml