@startuml
'https://plantuml.com/sequence-diagram

class Libro{
-private  isbn;String
-private nombreLibro;String
-private nombreAutor;String
-private generoLibro;String
-private cantidadPaginas;int
-private String carril;String
+Libro(String isbn,String nombreLibro,String nombreAutor,String generoLibro
String cantidadPaginas,String carril)
+get´s()
+set´s()
}

class ListaLibro{
-arreglo:Libro[]
-int cantidadMaxima
-int cantidadActual
+ListaLibro(int cantidadMaxima):void
+buscar(String isbn):void
+optener(int pocicion);void
+agregar(Libro nuevoLibro):void
+eliminar(String isbn):void
}
ListaLibro"1" *---- "0...*"Libro:rentan

@enduml