@startuml
'https://plantuml.com/sequence-diagram

left to right direction

class CuentaBancaria{
-saldo
+CuentaBancaria(saldo inicial)
+getsaldo():int
+deposito(monto):void
+giro(monto):void

}


@enduml